---
- name: Prepare
  hosts: localhost
  connection: local
  tasks:
    - name: Generate instance name ( random 5 alphanum string, ex 'a1c13' )
      set_fact:
        vm_name: "{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=5') }}"
    - name: Create the VM
      theko2fi.multipass.multipass_vm:
        name: "{{ vm_name }}"
        cpus: 2
        memory: 2G
        disk: 8G
        state: started
    - name: Add the VM to the inventory
      ansible.builtin.add_host:
        name: "{{ vm_name }}"
        ansible_host: "{{ vm_name }}"
        ansible_connection: theko2fi.multipass.multipass
        ansible_python_interpreter: '/usr/bin/python3'
    - name: Execute in a present VM (command)
      theko2fi.multipass.multipass_vm_exec:
        name: "{{ vm_name }}"
        command: "/bin/sh -c 'ls -a'"